-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 22:13:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pyramid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pyramid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pyramid` DEFAULT CHARACTER SET utf8 ;
USE `pyramid` ;

-- -----------------------------------------------------
-- Table `pyramid`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pyramid`.`customers` (
  `cusId` INT NOT NULL AUTO_INCREMENT,
  `cusName` VARCHAR(45) NOT NULL,
  `cusNIC` VARCHAR(45) NOT NULL,
  `cusEmail` VARCHAR(150) NOT NULL,
  `cusAddress` VARCHAR(150) NOT NULL,
  `cusSecondAddress` VARCHAR(45) NULL,
  `cusTP` VARCHAR(45) NOT NULL,
  `cusSecondTP` VARCHAR(45) NULL,
  `cusWhatsApp` VARCHAR(45) NULL,
  `referral` VARCHAR(45) NULL,
  `secondReferral` VARCHAR(45) NULL,
  `productCode` VARCHAR(45) NULL,
  `cusStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`cusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pyramid`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pyramid`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(255) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  `userStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
